# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: author

# A list of team reviewers to be added to pull requests (GitHub team slug)
reviewers:
  - ae-utbm/sith-3-developers

# Number of reviewers has no impact on GitHub teams
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 0