stages:
  - test

test:
  stage: test
  script:
  - env
  - apt-get update
  - apt-get install -y gettext libxapian-dev libgraphviz-dev
  - pip install poetry
  - poetry install -E testing
  - mkdir -p /dev/shm/search_indexes
  - ln -s /dev/shm/search_indexes sith/search_indexes
  - poetry run ./manage.py compilemessages
  - poetry run coverage run ./manage.py test
  - poetry run coverage html
  - poetry run coverage report
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip_tests"
  cache:
    paths:
      - .cache/pip_tests
  artifacts:
    paths:
      - coverage_report/

black:
  stage: test
  script:
    - pip install -U black
    - black --check .
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip_black"
  cache:
    paths:
      - .cache/pip_black
