stages:
  - test

test:
  stage: test
  script:
  - env
  - apt-get update
  - apt-get install -y gettext python3-xapian libgraphviz-dev
  - pushd /usr/lib/python3/dist-packages/xapian && ln -s _xapian* _xapian.so && popd
  - export PYTHONPATH="/usr/lib/python3/dist-packages:$PYTHONPATH"
  - python -c 'import xapian' # Fail immediately if there is a problem with xapian
  - pip install -U -r requirements.txt
  - pip install -U coverage
  - mkdir -p /dev/shm/search_indexes
  - ln -s /dev/shm/search_indexes sith/search_indexes
  - ./manage.py compilemessages
  - coverage run ./manage.py test
  - coverage html
  - coverage report
  - cd doc
  - make html # Make documentation
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip_tests"
  cache:
    paths:
      - .cache/pip_tests
  artifacts:
    paths:
      - coverage_report/

black:
  stage: test
  script:
    - pip install -U black
    - black --check .
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip_black"
  cache:
    paths:
      - .cache/pip_black
