name: Unit Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unittests:
    runs-on: ubuntu-latest

    steps:
      - run: echo 'Dry test'
  
  lint:
    runs-on: ubuntu-latest

    steps:
     - run: echo 'Dry lint'


